const CITIES = [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Gweru",
    "Kwekwe",
    "Masvingo",
    "Norton",
    "Kadoma",
    "Chegutu",
    "Chinhoyi",
    "Marondera",
    "Sakubva",
    "Bindura",
    "Hwange",
    "Beitbridge",
    "Chiredzi",
    "Rusape",
    "Zvishavane",
    "Chipinge",
    "Karoi",
    "Victoria Falls",
    "Redcliff",
    "Mukumbura",
    "Kariba",
    "Shurugwi",
    "Ruwa",
    "Murehwa",
    "Mvurwi",
    "Kezi",
    "Plumtree",
    "Gwanda",
    "Mutoko",
    "Mhangura",
    "Shamva",
    "Chivhu",
    "Mazoe",
    "Buhera",
    "Chimanimani",
    "Mount Darwin",
    "Banket",
    "Guruve",
    "Nyanga",
    "Goromonzi",
    "Arcturus",
    "Darwendale",
    "Lupane"
]

export default CITIES;